// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WS.Data.EF;

namespace WS.Data.Migrations
{
    [DbContext(typeof(WSDbContext))]
    [Migration("20221229091953_UpdateSeed_V3")]
    partial class UpdateSeed_V3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("WS.Data.Entities.Chapter", b =>
                {
                    b.Property<Guid>("IdChapter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Collector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdStory")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TitleChap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChapter");

                    b.HasIndex("IdStory");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            IdChapter = new Guid("b964e204-3d89-4478-b993-c5e2df10b214"),
                            Collector = "Nguoi suu tam",
                            Content = "Noi dung",
                            CreateDate = new DateTime(2022, 12, 29, 16, 19, 53, 341, DateTimeKind.Local).AddTicks(6806),
                            IdStory = "28887e0e-b47b-44b5-bce7-274658f14c31",
                            TitleChap = "Tieu de chap 1"
                        },
                        new
                        {
                            IdChapter = new Guid("27cddef8-0ff7-47eb-952c-4ff5706a190e"),
                            Collector = "Nguoi suu tam",
                            Content = "Noi dung",
                            CreateDate = new DateTime(2022, 12, 29, 16, 19, 53, 341, DateTimeKind.Local).AddTicks(8502),
                            IdStory = "28887e0e-b47b-44b5-bce7-274658f14c31",
                            TitleChap = "Tieu de chap 2"
                        },
                        new
                        {
                            IdChapter = new Guid("9a660bb4-8913-4a7c-abc3-b85ffab71500"),
                            Collector = "Nguoi suu tam",
                            Content = "Noi dung",
                            CreateDate = new DateTime(2022, 12, 29, 16, 19, 53, 341, DateTimeKind.Local).AddTicks(8580),
                            IdStory = "28887e0e-b47b-44b5-bce7-274658f14c31",
                            TitleChap = "Tieu de chap 3"
                        });
                });

            modelBuilder.Entity("WS.Data.Entities.Comment", b =>
                {
                    b.Property<string>("IdComment")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCom")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdStory")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateCom")
                        .HasColumnType("datetime2");

                    b.HasKey("IdComment");

                    b.HasIndex("IdStory");

                    b.HasIndex("IdUser");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WS.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WS.Data.Entities.Story", b =>
                {
                    b.Property<string>("IdStory")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Collector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAcept")
                        .HasColumnType("bit");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int>("NumberChap")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleStory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStory");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            IdStory = "28887e0e-b47b-44b5-bce7-274658f14c31",
                            Author = "Tac gia",
                            Collector = "Nguoi suu tam",
                            CreateDate = new DateTime(2022, 12, 29, 16, 19, 53, 339, DateTimeKind.Local).AddTicks(9099),
                            ImageFileName = "null.jpg",
                            IsAcept = true,
                            IsComplete = false,
                            NumberChap = 0,
                            PublishDate = new DateTime(2022, 12, 29, 16, 19, 53, 341, DateTimeKind.Local).AddTicks(4046),
                            Summary = "Tom tat",
                            TitleStory = "Tieu de truyen 3"
                        },
                        new
                        {
                            IdStory = "c7f95997-e1e6-4714-bf21-c4ac5d3ac4b2",
                            Author = "Tac gia 2",
                            Collector = "Nguoi suu tam 2",
                            CreateDate = new DateTime(2022, 12, 29, 16, 19, 53, 341, DateTimeKind.Local).AddTicks(5453),
                            ImageFileName = "null.jpg",
                            IsAcept = true,
                            IsComplete = false,
                            NumberChap = 0,
                            PublishDate = new DateTime(2022, 12, 29, 16, 19, 53, 341, DateTimeKind.Local).AddTicks(5478),
                            Summary = "Tom tat 2",
                            TitleStory = "Tieu de truyen 3"
                        },
                        new
                        {
                            IdStory = "0c162623-fda4-46a3-b647-d8dd7a60b21c",
                            Author = "Tac gia 3",
                            Collector = "Nguoi suu tam 3",
                            CreateDate = new DateTime(2022, 12, 29, 16, 19, 53, 341, DateTimeKind.Local).AddTicks(5517),
                            ImageFileName = "null.jpg",
                            IsAcept = true,
                            IsComplete = false,
                            NumberChap = 0,
                            PublishDate = new DateTime(2022, 12, 29, 16, 19, 53, 341, DateTimeKind.Local).AddTicks(5519),
                            Summary = "Tom tat 3",
                            TitleStory = "Tieu de truyen 3"
                        });
                });

            modelBuilder.Entity("WS.Data.Entities.Topic", b =>
                {
                    b.Property<string>("IdTopic")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameTopic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTopic");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            IdTopic = "3c7d4dfd-8fdc-4bf5-8fe8-1c33afd8eb7a",
                            NameTopic = "Tien hiep"
                        },
                        new
                        {
                            IdTopic = "2959b043-e266-4397-ba66-0beef768c72b",
                            NameTopic = "Kiem hiep"
                        });
                });

            modelBuilder.Entity("WS.Data.Entities.TopicInStory", b =>
                {
                    b.Property<string>("IdStory")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdTopic")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdStory", "IdTopic");

                    b.HasIndex("IdTopic");

                    b.ToTable("TopicInStory");
                });

            modelBuilder.Entity("WS.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WS.Data.Entities.UserHistoryChapter", b =>
                {
                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChapter")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUser", "IdChapter");

                    b.HasIndex("IdChapter");

                    b.ToTable("UserHistoryChapters");
                });

            modelBuilder.Entity("WS.Data.Entities.UserLikeStory", b =>
                {
                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdStory")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdUser", "IdStory");

                    b.HasIndex("IdStory");

                    b.ToTable("UserLikeStories");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("WS.Data.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("WS.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("WS.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("WS.Data.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WS.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("WS.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WS.Data.Entities.Chapter", b =>
                {
                    b.HasOne("WS.Data.Entities.Story", "Story")
                        .WithMany("Chapters")
                        .HasForeignKey("IdStory");
                });

            modelBuilder.Entity("WS.Data.Entities.Comment", b =>
                {
                    b.HasOne("WS.Data.Entities.Story", "Story")
                        .WithMany("Comments")
                        .HasForeignKey("IdStory");

                    b.HasOne("WS.Data.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WS.Data.Entities.TopicInStory", b =>
                {
                    b.HasOne("WS.Data.Entities.Story", "Story")
                        .WithMany("ListTopicInStory")
                        .HasForeignKey("IdStory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WS.Data.Entities.Topic", "Topic")
                        .WithMany("ListTopicInStory")
                        .HasForeignKey("IdTopic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WS.Data.Entities.UserHistoryChapter", b =>
                {
                    b.HasOne("WS.Data.Entities.Chapter", "Chapter")
                        .WithMany("UserHistoryChapters")
                        .HasForeignKey("IdChapter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WS.Data.Entities.User", "User")
                        .WithMany("UserHistoryChapters")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WS.Data.Entities.UserLikeStory", b =>
                {
                    b.HasOne("WS.Data.Entities.Story", "Story")
                        .WithMany("UserLikeStories")
                        .HasForeignKey("IdStory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WS.Data.Entities.User", "User")
                        .WithMany("UserLikeStories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
